
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView inputTB;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView outputTB;

	private global::Gtk.ComboBox alphabetControl;

	private global::Gtk.ComboBox directionControl;

	private global::Gtk.CheckButton aproxBrackets;

	private global::Gtk.CheckButton oddLetters;

	private global::Gtk.CheckButton spacesColons;

	private global::Gtk.Button button1;

	private global::Gtk.Button convButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 150;
		this.HeightRequest = 150;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Janky Gjallarhorn");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 300;
		this.GtkScrolledWindow.HeightRequest = 400;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.inputTB = new global::Gtk.TextView();
		this.inputTB.CanFocus = true;
		this.inputTB.Name = "inputTB";
		this.inputTB.WrapMode = ((global::Gtk.WrapMode)(3));
		this.GtkScrolledWindow.Add(this.inputTB);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w2.X = 31;
		w2.Y = 30;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.WidthRequest = 300;
		this.GtkScrolledWindow1.HeightRequest = 400;
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.outputTB = new global::Gtk.TextView();
		this.outputTB.CanFocus = true;
		this.outputTB.Name = "outputTB";
		this.outputTB.WrapMode = ((global::Gtk.WrapMode)(3));
		this.GtkScrolledWindow1.Add(this.outputTB);
		this.fixed1.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow1]));
		w4.X = 635;
		w4.Y = 30;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.alphabetControl = global::Gtk.ComboBox.NewText();
		this.alphabetControl.AppendText(global::Mono.Unix.Catalog.GetString("Elder Futhark"));
		this.alphabetControl.AppendText(global::Mono.Unix.Catalog.GetString("Younger Futhark"));
		this.alphabetControl.AppendText(global::Mono.Unix.Catalog.GetString("Anglo Saxon"));
		this.alphabetControl.AppendText(global::Mono.Unix.Catalog.GetString("Medieval"));
		global::Gtk.Tooltips w5 = new Gtk.Tooltips();
		w5.SetTip(this.alphabetControl, "Runic Alphabet", "Runic Alphabet");
		this.alphabetControl.WidthRequest = 175;
		this.alphabetControl.HeightRequest = 35;
		this.alphabetControl.Name = "alphabetControl";
		this.fixed1.Add(this.alphabetControl);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.alphabetControl]));
		w6.X = 399;
		w6.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.directionControl = global::Gtk.ComboBox.NewText();
		this.directionControl.AppendText(global::Mono.Unix.Catalog.GetString("Letters --> Runes"));
		this.directionControl.AppendText(global::Mono.Unix.Catalog.GetString("Runes --> Letters"));
		this.directionControl.WidthRequest = 175;
		this.directionControl.HeightRequest = 35;
		this.directionControl.Name = "directionControl";
		this.fixed1.Add(this.directionControl);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.directionControl]));
		w7.X = 399;
		w7.Y = 279;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.aproxBrackets = new global::Gtk.CheckButton();
		this.aproxBrackets.CanFocus = true;
		this.aproxBrackets.Name = "aproxBrackets";
		this.aproxBrackets.Label = global::Mono.Unix.Catalog.GetString("Remove aproximation brackets.");
		this.aproxBrackets.DrawIndicator = true;
		this.aproxBrackets.UseUnderline = true;
		this.fixed1.Add(this.aproxBrackets);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.aproxBrackets]));
		w8.X = 364;
		w8.Y = 337;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.oddLetters = new global::Gtk.CheckButton();
		this.oddLetters.CanFocus = true;
		this.oddLetters.Name = "oddLetters";
		this.oddLetters.Label = global::Mono.Unix.Catalog.GetString("Aproximate special characters.");
		this.oddLetters.DrawIndicator = true;
		this.oddLetters.UseUnderline = true;
		this.fixed1.Add(this.oddLetters);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.oddLetters]));
		w9.X = 364;
		w9.Y = 368;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spacesColons = new global::Gtk.CheckButton();
		this.spacesColons.CanFocus = true;
		this.spacesColons.Name = "spacesColons";
		this.spacesColons.Label = global::Mono.Unix.Catalog.GetString("Replace spaces with colons.");
		this.spacesColons.DrawIndicator = true;
		this.spacesColons.UseUnderline = true;
		this.fixed1.Add(this.spacesColons);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spacesColons]));
		w10.X = 364;
		w10.Y = 399;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 175;
		this.button1.HeightRequest = 25;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w11.X = 399;
		w11.Y = 188;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.convButton = new global::Gtk.Button();
		this.convButton.WidthRequest = 175;
		this.convButton.HeightRequest = 50;
		this.convButton.CanFocus = true;
		this.convButton.Name = "convButton";
		this.convButton.UseUnderline = true;
		this.convButton.Label = global::Mono.Unix.Catalog.GetString("Convert");
		this.fixed1.Add(this.convButton);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.convButton]));
		w12.X = 399;
		w12.Y = 141;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 967;
		this.DefaultHeight = 472;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.clearButton);
		this.convButton.Clicked += new global::System.EventHandler(this.convClicked);
	}
}
